import function.webapi.chat
import function.webapi.joke
import function.webapi.maxim
import function.webapi.sm
import function.webapi.trick
import function.webapi.weather
import function.webapi.ip
import function.webapi.ping
import function.webapi.py3exec